### ISSUE TITLE
调一下git配置啊,邮件设置好像错了...

### ISSUE THREAD

**Issue by ekzist** [posclegom/programthinkmirror#2]
![image](https://user-images.githubusercontent.com/36391033/36267772-a105f618-126c-11e8-88e5-8b2b34959550.png)
(https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/)

**Comment by posclegom** [comment]
多谢ekzist，愚弟是故意没有设置email地址滴，主要是因为不想被spam。如果对愚弟的仓库有任何问题的话请留言于此公告板里，愚弟将在第一时间尽快回复。

**Comment by ekzist** [comment]
不想被spam可以设置成
posclegom@users.noreply.github.com

**Comment by posclegom** [comment]
收到，多谢ekzist兄提点！
